name: CI

on:
  push: {branches: main}
  pull_request: {branches: main}
  workflow_dispatch:
  repository_dispatch:

jobs:
  ci:
    name: Test & Formatting
    runs-on: ubuntu-latest
    env: {MIX_ENV: test}
    steps:
      - name: Check out source code
        uses: actions/checkout@v2
      - name: Restore mix cache
        uses: actions/cache@v2
        with:
          path: deps
          key: ${{ runner.os }}-mix-${{ hashFiles('mix.lock') }}
          restore-keys: ${{ runner.os }}-mix-
      - name: Set up Elixir
        uses: actions/setup-elixir@v1
        with: {otp-version: 22.x, elixir-version: 1.10.x}
      - name: Fetch mix dependencies
        run: mix deps.get
      - name: Check formatting
        run: mix format --check-formatted
      - name: Run tests
        run: mix test
